### ISSUE TITLE
請問這怎麼deploy到Heroku

### ISSUE THREAD

**Issue by ChaoTzuJung** [tw0517tw/bottender-order-example#1]
之前我是這樣寫，但看完你們的套件後，並都用好heroku環境了，但是line的console需要Webhook URL，
所以我的SSL require需要 https://{MY_PROJECT}.herokuapp.com/某某值，我卡在這關，不知道你們的套件有什麼樣的寫法？
```
const app = express();

//驗證數位簽章並解析JSON資料
const linebotParser = bot.parser();

//處理首頁請求
app.get('/',function(req,res){
  res.send('Deploy Successfully!');
});

//處理line訊息的伺服器請求(linewebhook就是我的某某值)
app.post('/linewebhook', linebotParser);
```

**Comment by tw0517tw** [comment]
Heroku 提供的網址已經是 https 了，直接把網址填入 LINE developers 後台應該就可以了？

乍看之下不太清楚你遇到的問題是什麼，可以再描述得更詳細一些嗎？

**Comment by ChaoTzuJung** [comment]
感謝您的回覆！！其實主要是網路上的教學是說line有提供linebotParser去讓app做post
然後app.post('/linewebhook', linebotParser);這行程式的linewebhook這個字可以貼到如下行
https://{MY_PROJECT}.herokuapp.com/linewebhook，我就成功做好SSL require
但現在如果直接貼上https://{MY_PROJECT}.herokuapp.com/或是
https://{MY_PROJECT}.herokuapp.com/callback在line 的console會出現錯誤警告
An error occurred when sending the webhook. 或是
The webhook returned an invalid HTTP status code. (The expected status code is 200.)

不知道該怎處理這塊

原本express有提供app這個api可以用，現在這個bottender工具改用createServer，突然就不知道該怎處理get跟post這塊

**Comment by tw0517tw** [comment]
這行程式碼

```js
app.post('/linewebhook', linebotParser);
```

的意思是說當你這個 server(`app`) 遇到 POST 到 `/linewebhook` 這個網址的 request 的時候就使用 `linebotParser` 這個 middeleware 處理，所以如果你想要用其他的網址當 webhook URL 的話，就要寫成例如

```js
app.post('/callback', linebotParser);
```

這樣子的話你就可以在 LINE 後台註冊 `https://{xxx}.herokuapp.com/callback` 這個網址讓 LINE 發 request 給你。

**Comment by ChaoTzuJung** [comment]
那你們的這行範例依然可以import app這個參數作使用嗎？
const { createServer } = require('bottender/express');

**Comment by tw0517tw** [comment]
在我這個 repo 的範例中，是用直接網址根目錄處理 request，所以要修改的是 
https://github.com/tw0517tw/bottender-order-example/blob/master/index.js#L23-L25
```js
server.listen(5000, () => {
  console.log('server is running on 5000 port...');
});
```
把 server listen 的 port 從 `5000` 改成從環境變數 `PORT` 拿，也就是
```js
server.listen(process.env.PORT)
```
之後在 LINE 後台直接輸入 `https://{xxx}.herokuapp.com/`

在 Bottender 框架中，`createServer` 回傳的 server 物件已經處理好註冊 middleware 的事情了。
