### ISSUE TITLE
私聊機器人正常回應，加進群組後不會回應...

### ISSUE THREAD

**Issue by ChaoTzuJung** [tw0517tw/bottender-order-example#2]
您好：
想請問一下，這在多人群組內要可以回應像是揪團..下訂單等
是有要另外設定嗎？

因為怎麼下關鍵字都只有回line後台預設的自動回應訊息

**Comment by tw0517tw** [comment]
我的後台設定長這樣讓你參考看看，我當時沒印象有做其他設定，程式直接可以在群組內運作
![default](https://user-images.githubusercontent.com/1003146/39002424-1be3738e-442b-11e8-977c-b1501c35ec78.png)

**Comment by ChaoTzuJung** [comment]
群組問題解決了XD
請問取消訂單無效是正常的嗎？
![image alt](https://i.imgur.com/mpIfekT.jpg)

**Comment by tw0517tw** [comment]
在我這邊沒有問題，你做了什麼修改嗎?

**Comment by ChaoTzuJung** [comment]
應該是我變數名稱設錯
這個repo是用中文當變數～～真的超用心！！推
